### ISSUE TITLE
ApmView's raises AttributeError when trying to get a `view_name`

### ISSUE THREAD

**Issue by leandrodesouzadev** [plathanus-tech/django-apm#9]
Previous discussion #3

**Comment by NiklasMerz** [comment]
I just tried version 0.2.0 and it works without errors. Thanks for this refactoring and new release!

I realized that the view name is no longer the real package name but `views` in my case got replaced with `dj`. Is this intentional? 

![image](https://user-images.githubusercontent.com/3585860/199433086-ae88abf1-b356-4d28-9048-0d2c2f0e858d.png)

**Comment by leandrodesouzadev** [comment]
Hey @NiklasMerz!
Yeah that was intentional, now the "views" was stripped off. The naming will be:
For Django views: "app.dj.class_or_func_name"
For Drf views: "app.drf.class_or_func_name"

I think this will help separating them.


I'm now thinking that I haven't created a test case for a ViewSet. I'm won't be working today due to a holiday here in Brazil. Are you able to give a try using a DRF ViewSet?

**Comment by NiklasMerz** [comment]
Alright that's fine for me. It tracks my important views perfectly fine.

I just added the `ApmView` mixin to a rest_framework viewset and it looks like the requests are not recorded. Class looks like this:


```python
class ProjectViewSet(viewsets.ModelViewSet, ApmView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
```

Have a nice holiday. I wasn't working yesterday because of a holiday in Germany :-).
